
					<img id="row_1390926495159" class="element" src="https://microweber.com/userfiles/media/banner_modules_1.png" alt="" style="margin: 12px 0px; padding: 0px; box-sizing: border-box; border: none; max-width: 100%; vertical-align: middle; font-family: Arial, Helvetica, sans-serif; outline: none; position: relative; display: inline-block; clear: both; transition: none !important; -webkit-transition: none !important; -webkit-transform-origin: 50% 50%; color: rgb(40, 40, 40); font-size: 16px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 23px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><div id="row_1390926495160" class="element">  <div class="element text" data-mw-title="Text" data-type="text" id="row_1390926495161">
<p id="row_1390926495162" class="element lipsum">The editable regions are the places where the users can drag and drop modules and edit content in real time. <br class=""></p>
<p id="row_1390926495163" class="element lipsum">You can define as few or as many regions that you like, also you can define their scope.</p>
</div>
<h3 id="row_1390926495165" class="element">Creating editable field<br class="">
</h3>
<p id="row_1390926495166" class="element">You can define editable regions in your template where the user will be able to type text and <em class="">Drag and Drop</em> modules</p>  <ul class="">
<li class=""><b class="">You must add class "edit"</b></li> </ul>
<p class="element" id="row_1390926495167">Example: <br class=""></p>
<div class="highlight highlight-html element" id="row_1390926495168">
<p id="row_1390926495169" class="element">
</p>
<code class=""><span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"edit"</span>  <span class="na">field=</span><span class="s">"your_region_name"</span> <span class="na">rel=</span><span class="s">"content"</span><span class="nt">&gt;</span>       <span class="nt"><br class="" id="temp1390905218516">    &lt;div</span> <span class="na">class=</span><span class="s">"element"</span><span class="nt">&gt;</span>Edit your content<span class="nt">&lt;/div&gt;</span> <span class="nt"><br class="" id="temp1390905218678">&lt;/div&gt;</span> </code>After that you must set few attributes on the html element in your template<p id="row_1390926495170" class=" element"></p>
</div>  <h3 id="row_1390926495171" class="element"> <a name="the-field-attribute" class="anchor" href="#the-field-attribute"><span class="octicon octicon-link"></span></a>The "field" attribute</h3>    <p id="row_1390926495172" class="element">The field attribute will help you to split your content into multiple content-editable fields</p>  <ul class="">
<li class="">Add attribute <em class="">field="some name"</em> and set the name of your field.</li> <li class="">The main editable region must have  <em class="">field="content"</em> </li> </ul>
<h3 id="row_1390926495173" class="element"> <a name="the-rel-attribute" class="anchor" href="#the-rel-attribute"><span class="octicon octicon-link"></span></a>The "rel" attribute</h3>    <p id="row_1390926495174" class="element">The <code class="">rel</code> attribute is responsible for the <a class="" target="_self" href="http://en.wikipedia.org/wiki/Scope_(computer_science)">scope</a> of your content-editable field. You can define custom scope and reuse the content of the editable regions across the whole website.</p>  <ul class="">
<li class="">Add attribute <code class=""><em class="">rel</em> </code>and set the scope of your field.  <ul class="">
<li class=""> <em class=""></em><code class=""><em class="">rel="content"</em></code> - changes for ever page or post</li> <li class=""> <em class=""></em><code class=""><em class="">rel="global"</em></code> - changes for the whole site</li> <li class=""> <em class=""></em><code class=""><em class="">rel="page"</em></code> - changes for every page and sub-page<br class="">
</li> <li class=""> <em class=""><code class="">rel="post"</code></em> - changes for every post</li> <li class=""> <em class=""><code class="">rel="inherit"</code></em> - changes for every main page, but not is sub-pages and posts</li> <li class=""> <em class=""></em><code class=""><em class="">rel="your_custom_rel"</em></code> you can define your own scope</li> </ul>
</li> </ul>
<h3 id="row_1390926495175" class="element"> <a name="the-rel-id-attribute" class="anchor" href="#the-rel-id-attribute"><span class="octicon octicon-link"></span></a>The "rel-id" attribute</h3>    <p id="row_1390926495176" class="element">The <code class="">rel-id</code> attribute is <em class="">optional</em> and allows you to pull editable regions that belong to another content</p>
<h3 id="row_1390926495177" class="element">Add editable fields in your template<br class="">
</h3>
<p id="row_1390926495178" class="element"><img id="row_1390926495179" class="element" src="http://microweber.com/userfiles/media/editable_regions_classes.png"></p>  <h4 id="row_1390926495180" class="element"> <a name="sample-layout-with-sidebar" class="anchor" href="#sample-layout-with-sidebar"><span class="octicon octicon-link"></span></a>Sample layout with sidebar<br class="" id="temp1390924754788">
</h4>
<p id="row_1390926495181" class="element"><i class="">note the usage of the rel tag</i></p>    <div id="row_1390926495182" class="highlight highlight-html element">
<p id="row_1390926495183" class="element">  </p>
<code class="">&lt;?php<br class="">/*<br class=""><br class="">type: layout<br class="">content_type: dynamic<br class="">name: Blog<br class="">description: Blog<br class="">*/<br class="">?&gt;<br class="">&lt;?php include TEMPLATE_DIR. "header.php"; ?&gt;<br class=""><br class="">&lt;div id="content"&gt;<br class=""><br class="">	&lt;div class="edit"  field="content" rel="page"&gt;<br class="">	    &lt;h2&gt;My Page&lt;/h2&gt;<br class="">	    &lt;p&gt;My content&lt;/p&gt;<br class="">	&lt;/div&gt;<br class="">&lt;/div&gt;<br class=""><br class="">&lt;div id="sidebar"&gt;<br class="">	&lt;div class="edit"  field="sidebar" rel="inherit"&gt;<br class="">	    &lt;h2&gt;Sidebar&lt;/h2&gt;<br class="">	    &lt;p&gt;This content is the same for every sub-page&lt;/p&gt;<br class="">	&lt;/div&gt;<br class="">&lt;/div&gt;<br class=""><br class="">&lt;?php include TEMPLATE_DIR. "footer.php"; ?&gt;</code> <p id="row_1390926495184" class=" element"></p>
</div>
<h3 id="row_1390926495185" class="element">Editable regions from another page</h3>  <p id="row_1390926495186" class="element">The <code class="">rel-id</code> attribute will pull the content from another place</p>  <div id="row_1390926495187" class="highlight highlight-html element">
<p id="row_1390926495188" class="element">  </p>
<code class="">&lt;h2 class="edit"  field="title" rel="content" rel-id="5"&gt; The post title goes here &lt;/h2&gt;  <br class="">&lt;div class="edit"  field="content" rel="content" rel-id="5"&gt;       <br class="">	The post content will appear here <br class="">&lt;/div&gt;  <br class="">&lt;div class="edit"  field="my_custom_region" rel="content" rel-id="5"&gt; <br class="">	You can pull any region <br class="">&lt;/div&gt;</code>
<p id="row_1390926495189" class=" element"></p>
</div>
<h3 id="row_1390926495190" class="element">Editable regions anywhere</h3>  <p id="row_1390926495191" class="element">Because you can define custom <code class="">rel</code> and <code class="">rel-id</code> attributes you can use editable regions from anywhere and the parser will replace them with the actual content from the database.</p>
<p id="row_1390926495192" class="element">Here is how we can make editable region in our module: <a href="https://github.com/microweber/microweber/blob/master/userfiles/modules/contact_form/templates/default.php#L27" class="">example</a></p>  <code class=""><code class="">&lt;div class="edit" field="my_module_title" rel="my_module" rel-id="my_custom_id"&gt;<br class="" id="temp1390905224691"> Edit your text <br class="" id="temp1390905224917">&lt;/div&gt;  </code></code>
</div>
<h3 id="row_1390926495193" class="element">Custom editable regions <br class="">
</h3>Setting custom field and rel value will allow you to have custom regions for your template or module. <br class=""><code class=""><code class="">&lt;div class="edit" field="my_field_name" rel="my_rel"&gt;<br class="" id="temp1390905224691"> Editable field <br class="" id="temp1390905224917">&lt;/div&gt;  </code></code><p id="row_1390926495194" class=" element"></p>
				